using System.Text.Json.Serialization;
using AnimeGoNet.App.Api;
using AnimeGoNet.App.Downloads;
using AnimeGoNet.App.Feeds;

namespace AnimeGoNet.App.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(LegacyApiResponse<PingData>))]
[JsonSerializable(typeof(LegacyApiResponse<string>))]
[JsonSerializable(typeof(LegacyPluginConfigUploadRequest))]
[JsonSerializable(typeof(LegacyApiResponse<LegacyPluginResponse?>))]
[JsonSerializable(typeof(LegacyApiResponse<LegacyPluginConfigResponse?>))]
[JsonSerializable(typeof(LegacyApiResponse<LegacyBoltListResponse?>))]
[JsonSerializable(typeof(LegacyApiResponse<LegacyBoltGetResponse?>))]
[JsonSerializable(typeof(LegacyApiResponse<LegacyBoltDeleteResponse?>))]
[JsonSerializable(typeof(RuntimeStatus))]
[JsonSerializable(typeof(ConfigurationResponse))]
[JsonSerializable(typeof(ConfigurationFieldLockResponse))]
[JsonSerializable(typeof(ConfigurationUpdateRequest))]
[JsonSerializable(typeof(ConfigurationPreviewResponse))]
[JsonSerializable(typeof(ConfigurationWriteResponse))]
[JsonSerializable(typeof(IngestBatchRequest))]
[JsonSerializable(typeof(RssIngestRequest))]
[JsonSerializable(typeof(MikanRssIngestResult))]
[JsonSerializable(typeof(LegacyRssRequest))]
[JsonSerializable(typeof(LegacyApiResponse<MikanRssIngestResult?>))]
[JsonSerializable(typeof(IngestBatchResponse))]
[JsonSerializable(typeof(LegacyApiResponse<IngestBatchResponse?>))]
[JsonSerializable(typeof(DownloadListResponse))]
[JsonSerializable(typeof(DownloadDashboardSummary))]
[JsonSerializable(typeof(DownloadDetailResponse))]
[JsonSerializable(typeof(DownloadControlRequest))]
[JsonSerializable(typeof(DownloadControlResponse))]
[JsonSerializable(typeof(MikanWorkRuleRequest))]
[JsonSerializable(typeof(MikanWorkRuleResponse))]
[JsonSerializable(typeof(MikanWorkImpactResponse))]
[JsonSerializable(typeof(MikanWorkRematchRequest))]
[JsonSerializable(typeof(MikanWorkRematchResponse))]
[JsonSerializable(typeof(MikanTrustedOffsetListResponse))]
[JsonSerializable(typeof(MetadataRetryResponse))]
[JsonSerializable(typeof(MetadataTaskListResponse))]
[JsonSerializable(typeof(MetadataTaskDetailResponse))]
[JsonSerializable(typeof(MetadataAttemptListResponse))]
[JsonSerializable(typeof(AnimeSeasonListResponse))]
[JsonSerializable(typeof(AnimeSeasonDetailResponse))]
[JsonSerializable(typeof(AnimeSeasonCreateRequest))]
[JsonSerializable(typeof(AnimeSeasonRefreshRequest))]
[JsonSerializable(typeof(AnimeSeasonMutationResponse))]
[JsonSerializable(typeof(AnimeSeasonDeleteResponse))]
[JsonSerializable(typeof(DirectoryDatabaseStatusResponse))]
[JsonSerializable(typeof(DataUpdateStatusResponse))]
[JsonSerializable(typeof(DataUpdateActionResponse))]
[JsonSerializable(typeof(PendingTmdbListResponse))]
[JsonSerializable(typeof(PendingTmdbDetailResponse))]
[JsonSerializable(typeof(PendingTmdbRecoveryRequest))]
[JsonSerializable(typeof(PendingTmdbRecoveryResponse))]
[JsonSerializable(typeof(ApiErrorResponse))]
[JsonSerializable(typeof(DeletePreviewResponse))]
[JsonSerializable(typeof(CreateDeleteExecutionRequest))]
[JsonSerializable(typeof(CreateDeleteExecutionResponse))]
[JsonSerializable(typeof(DeleteExecutionStatusResponse))]
[JsonSerializable(typeof(RssRuleSetRequest))]
[JsonSerializable(typeof(RssRuleSetResponse))]
[JsonSerializable(typeof(RssRuleRollbackRequest))]
[JsonSerializable(typeof(RssRulePreviewRequest))]
[JsonSerializable(typeof(RssRulePreviewResponse))]
[JsonSerializable(typeof(SourceProfileCreateRequest))]
[JsonSerializable(typeof(SourceProfileUpdateRequest))]
[JsonSerializable(typeof(SourceProfileResponse))]
[JsonSerializable(typeof(SourceProfileListResponse))]
[JsonSerializable(typeof(SourceProfileDeleteResponse))]
[JsonSerializable(typeof(DownloaderInstanceResponse))]
[JsonSerializable(typeof(DownloaderInstanceListResponse))]
[JsonSerializable(typeof(DownloaderConnectionTestResponse))]
[JsonSerializable(typeof(DownloaderPathProbeResponse))]
[JsonSerializable(typeof(DownloaderInstanceUpsertRequest))]
[JsonSerializable(typeof(DownloaderConfigurationWriteResponse))]
[JsonSerializable(typeof(SourceRoutePreviewRequest))]
[JsonSerializable(typeof(SourceRoutePreviewResponse))]
[JsonSerializable(typeof(LegacyMikanFilterResponse))]
[JsonSerializable(typeof(LegacyMikanFilterWriteRequest))]
[JsonSerializable(typeof(LegacyMikanFilterImportRequest))]
[JsonSerializable(typeof(LegacyMikanFilterRollbackRequest))]
[JsonSerializable(typeof(LegacyMikanFilterPreviewRequest))]
[JsonSerializable(typeof(LegacyMikanFilterPreviewResponse))]
[JsonSerializable(typeof(QbittorrentTorrentInfo[]))]
[JsonSerializable(typeof(QbittorrentTorrentFile[]))]
internal sealed partial class ApiJsonContext : JsonSerializerContext;
